stages:
  - code

import_upstream_dbt_git_repo_changes:
  rules:
  #only runs if you're on a main branch
    - if: '$CI_COMMIT_BRANCH =~ /^main/'
  stage: code
  image: python:3.7
  before_script:
    - echo "Started ${CI_JOB_NAME} - $(date)"
    - pip install dbt-snowflake
  script:
    - git clone https://gitlab.com/paulf-999/dbt_demo_vertical_proj_struct.git
    - cd bike_shop && dbt deps
    - git config --global user.name 'GitLab CI Worker'
    - git config --global user.email 'paulfry999@gmail.com'
    - git add dbt_packages/
    - git commit -m "Importing changes made in upstream dbt ('division data processing') git repo"
    - git push -u origin main
  after_script:
    - echo "Finished ${CI_JOB_NAME} - $(date)"
  allow_failure: false
