stages:
  - code

demo_workflow:
  rules:
  #only runs if you're on a main branch
    - if: '$CI_COMMIT_BRANCH =~ /^main/'
  stage: code
  image: python:latest
  before_script:
    - echo "Started ${CI_JOB_NAME} - $(date)"
    - pip install dbt-snowflake
  script:
    - cd bike_shop && dbt deps
    - git add bike_shop/dbt_modules/
    - git commit -m "Importing changes made in upstream dbt ('division data processing') git repo"
    - git push -u origin main
  after_script:
    - echo "Finished ${CI_JOB_NAME} - $(date)"
  allow_failure: false
