stages:
  - git-robot

import_upstream_dbt_git_repo_changes:
  stage: git-robot
  #only runs if you're on the main branch
  only:
    - main
  #doesn't run if the commit was performed by 'git-robot'
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^git-robot*/
  allow_failure: false
  image: python:3.7
  before_script:
    - echo "${CI_COMMIT_MESSAGE}"
    - echo "Started ${CI_JOB_NAME} - $(date)"
    - pip install dbt-snowflake==1.0.0
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - git config --global user.name 'GitLab CI Worker'
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - mkdir -p ~/.ssh
    - cat gitlab-known-hosts >> ~/.ssh/known_hosts
    - git clone git@gitlab.com:paulf-999/dbt_demo_vertical_proj_struct.git
  script:
    - cd dbt_demo_vertical_proj_struct/bike_shop && dbt deps
    - git add dbt_packages/
    - git commit -m "git-robot - importing changes made in upstream dbt ('division data processing') git repo"
    - git push -u origin main
  after_script:
    - echo "Finished ${CI_JOB_NAME} - $(date)"
