stages:
  - code

demo_workflow:
  rules:
  #only runs if you're on a main branch
    - if: '$CI_COMMIT_BRANCH =~ /^main/'
  stage: code
  image:
    name: apache/airflow:2.0.2-python3.7
    entrypoint: [""]
  before_script:
  - echo "Started ${CI_JOB_NAME} - $(date)"
  script:
    - pip install git
    - pip install dbt-snowflake
    - cd bike_shop && dbt deps
    - git add bike_shop/dbt_modules/
    - git commit -m "Changes made in upstream dbt (division processing) git repo"
    - git push -u origin main
  after_script:
    - echo "Finished ${CI_JOB_NAME} - $(date)"
  allow_failure: true
